site_name: Practicas de Grahru

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Practica 1.1: 1-1.md
    - Practica 1.2: 1-2.md

theme:
  name: material
  palette:
      scheme: slate
      primary: black
      accent: indigo
  font:
    text: Lora
